### PR TITLE
Alphabetize properties in README.md

### PR DESCRIPTION
**Pull request by nascosto**
I should be easier to find rules if they are ordered alphabetically.

### CODE REVIEW

**Comment by mik01aj** [comment]
I guess if you do so, then also the example config should be sorted.

**Comment by vBm** [comment]
This also fixes the broken link for `prefer-includes` since it says `pERfer`

**Comment by nascosto** [comment]
Well, it didn't. But now it does. I can update the example config as well.

**Comment by nascosto** [comment]
Where is this example config?

**Comment by mik01aj** [comment]
It used to be in the readme, but not anymore. Now it's in [`src/index.js`](https://github.com/wix/eslint-plugin-lodash/blob/master/src/index.js).

**Comment by ganimomer** [comment]
That's an actual config you can use, and it's already alphabetised AFAIK.

**Comment by ganimomer** [comment]
Squashed and merged. Thanks!

**Pull request merged**
